uiaflights/uiaflights/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace uiaflights.Models
{
    public class Booking
    {
        public int ID { get; set; }
        public Guid CustomerId { get; set; }
        public Customer Customer { get; set; }
        [Display(Name = "Booking Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime BookingDate { get; set; }
        public String Status { get; set; }
        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        public decimal? Total { get; set; }
        public ICollection<Ticket> Tickets { get; set; }
    }
}

uiaflights/uiaflights/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using uiaflights.Data;
using uiaflights.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using uiaflights.Models.FlightBookingViewModels;

namespace uiaflights.Controllers
{
    [Authorize]
    public class BookingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public BookingsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Bookings
        public async Task<IActionResult> Index(string sortOrder)
        {
            var user = await _userManager.GetUserAsync(User);
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            //ViewData["FlightSortParm"] = sortOrder == "flight_asc" ? "flight_desc" : "flight_asc";
            //ViewData["OriginSortParm"] = sortOrder == "origin_asc" ? "origin_desc" : "origin_asc";
            //ViewData["DestSortParm"] = sortOrder == "dest_asc" ? "dest_desc" : "dest_asc";
            //ViewData["DateSortParm"] = sortOrder == "date_asc" ? "date_desc" : "date_asc";
            var bookings = from b in _context.Bookings
                           .Include(b => b.Customer)
                           .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Origin)
                           .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Dest)
                           .Include(b => b.Tickets).ThenInclude(t => t.Passenger)
                           .Where(b => b.Customer == (Customer)user)
                           select b;
            switch (sortOrder)
            {
                //case "date_desc":
                //    bookings = bookings.OrderByDescending(b => b.Tickets.FirstOrDefault().Flight.DepartureDateTime);
                //    break;
                //case "date_asc":
                //    bookings = bookings.OrderBy(b => b.Tickets.FirstOrDefault().Flight.DepartureDateTime);
                //    break;
                //case "dest_desc":
                //    bookings = bookings.OrderByDescending(b => b.Tickets.FirstOrDefault().Flight.Dest.Name);
                //    break;
                //case "dest_asc":
                //    bookings = bookings.OrderBy(b => b.Tickets.FirstOrDefault().Flight.Dest.Name);
                //    break;
                //case "origin_desc":
                //    bookings = bookings.OrderByDescending(b => b.Tickets.FirstOrDefault().Flight.Origin.Name);
                //    break;
                //case "origin_asc":
                //    bookings = bookings.OrderBy(b => b.Tickets.FirstOrDefault().Flight.Origin.Name);
                //    break;
                //case "flight_desc":
                //    bookings = bookings.OrderByDescending(b => b.Tickets.FirstOrDefault().Flight.FlightNo);
                //    break;
                //case "flight_asc":
                //    bookings = bookings.OrderBy(b => b.Tickets.FirstOrDefault().Flight.FlightNo);
                //    break;
                //case "id_desc":
                //    bookings = bookings.OrderByDescending(b => b.ID);
                //    break;
                default:
                    bookings = bookings.OrderBy(b => b.ID);
                    break;
            }
            return View(await bookings.AsNoTracking().ToListAsync());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Customer)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Origin)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Dest)
                .Include(b => b.Tickets).ThenInclude(t => t.Passenger)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return NotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Customer)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Origin)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Dest)
                .Include(b => b.Tickets).ThenInclude(t => t.Passenger)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return NotFound();
            }
            FlightBookingViewModel fbvm = new FlightBookingViewModel
            {
                flight = booking.Tickets.FirstOrDefault().Flight,
                booking = booking
            };
            return View(fbvm);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Customer)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Origin)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Dest)
                .Include(b => b.Tickets).ThenInclude(t => t.Passenger)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again, and if the problem persists " +
                    "see your system administrator.";
            }

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var booking = await _context.Bookings
                .Include(b => b.Tickets)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return RedirectToAction("Index");
            }
            try
            {
                var tickets = booking.Tickets;
                foreach (Ticket t in tickets)
                {
                    _context.Tickets.Remove(t);
                }
                _context.Bookings.Remove(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.)
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
        }

        private bool BookingExists(int id)
        {
            return _context.Bookings.Any(e => e.ID == id);
        }
    }
}

uiaflights/uiaflights/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using uiaflights.Data;
using uiaflights.Models;
using Microsoft.AspNetCore.Identity;

namespace uiaflights.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public TicketsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Passenger)
                .Include(t => t.Booking)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Passenger)
                .Include(t => t.Booking)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (ticket == null)
            {
                return NotFound();
            }
            IEnumerable<string> classType = new string[] { "Economy", "Business", "First" };
            ViewData["ClassType"] = new SelectList(classType, ticket.CabinCl);
            return View(ticket);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ticketToUpdate = await _context.Tickets
                .Include(t => t.Passenger)
                .Include(t => t.Booking)
                .Include(t => t.Flight).ThenInclude(f => f.Tariff)
                .SingleOrDefaultAsync(t => t.ID == id);
            var bookingUrl = "/Bookings/Edit/" + ticketToUpdate.Booking.ID;
            if (await TryUpdateModelAsync<Ticket>(
                ticketToUpdate,
                "",
                t => t.Passenger, t => t.CabinCl))
            {
                try
                {
                    var oldPrice = ticketToUpdate.Price;
                    ticketToUpdate.Price = ticketToUpdate.Flight.Tariff.Single(t => t.CabinCl == ticketToUpdate.CabinCl).AdultFare;
                    ticketToUpdate.Booking.Total = ticketToUpdate.Booking.Total - oldPrice + ticketToUpdate.Price;
                    await _context.SaveChangesAsync();
                    return Redirect(bookingUrl);
                }
                catch (DbUpdateException /* ex */)
                {
                    //Log the error (uncomment ex variable name and write a log.)
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
            }
            IEnumerable<string> classType = new string[] { "Economy", "Business", "First" };
            ViewData["ClassType"] = new SelectList(classType, ticketToUpdate.CabinCl);
            return View(ticketToUpdate);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Passenger)
                .Include(t => t.Booking)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (ticket == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again, and if the problem persists " +
                    "see your system administrator.";
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Tickets
                .Include(t => t.Booking)
                .SingleOrDefaultAsync(m => m.ID == id);
            var bookingUrl = "/Bookings/Edit/" + ticket.Booking.ID;
            if (ticket == null)
            {
                return Redirect(bookingUrl);
            }
            try
            {
                ticket.Booking.Total = ticket.Booking.Total - ticket.Price;
                _context.Update(ticket.Booking);
                _context.Tickets.Remove(ticket);
                await _context.SaveChangesAsync();
                return Redirect(bookingUrl);
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.)
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.ID == id);
        }
    }
}

uiaflights/uiaflights/Views/Bookings/Delete.cshtml
@model uiaflights.Models.Booking

@{
    ViewData["Title"] = "Cancel Booking";
}

<h2>Cancel Booking</h2>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to cancel this booking?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BookingDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BookingDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        @if (Model.Tickets != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.FlightNo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.FlightNo)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.Origin)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Origin.Name) (@Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Origin.IATA)), @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Origin.City), @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Origin.Country)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.Dest)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Dest.Name) (@Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Dest.IATA)), @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Dest.City), @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Dest.Country)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.DepartureDateTime)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.DepartureDateTime) hrs
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.ArrivalDateTime)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.ArrivalDateTime) hrs
            </dd>
            <dd>
                <table class="table">
                    <tr>
                        <th>Ticket No</th>
                        <th>Passenger Name</th>
                        <th>Cabin Class</th>
                        <th>Price</th>
                    </tr>
                    @foreach (var item in Model.Tickets)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Passenger.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CabinCl)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                        </tr>
                    }
                </table>
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Total)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Total)
            </dd>
        }
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Cancel" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

uiaflights/uiaflights/Views/Bookings/Details.cshtml
@model uiaflights.Models.Booking

@{
    ViewData["Title"] = "Booking Details";
}

<h2>Booking Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BookingDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BookingDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        @if (Model.Tickets != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.FlightNo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.FlightNo)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.Origin)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Origin.Name) (@Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Origin.IATA)), @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Origin.City), @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Origin.Country)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.Dest)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Dest.Name) (@Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Dest.IATA)), @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Dest.City), @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.Dest.Country)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.DepartureDateTime)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.DepartureDateTime) hrs
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.ArrivalDateTime)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Tickets.FirstOrDefault().Flight.ArrivalDateTime) hrs
            </dd>
            <dd>
                <table class="table">
                    <tr>
                        <th>Ticket No</th>
                        <th>Passenger Name</th>
                        <th>Cabin Class</th>
                        <th>Price</th>
                    </tr>
                    @foreach (var item in Model.Tickets)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Passenger.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CabinCl)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                        </tr>
                    }
                </table>
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Total)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Total)
            </dd>
        }
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

uiaflights/uiaflights/Views/Bookings/Edit.cshtml
@model uiaflights.Models.FlightBookingViewModels.FlightBookingViewModel

@{
    ViewData["Title"] = "Edit Booking";
}

@section Styles {
    <link href="https://addtocalendar.com/atc/1.5/atc-style-blue.css" rel="stylesheet" type="text/css">
}

<h2>Edit Booking</h2>

<hr />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.booking.ID)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.booking.ID)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.booking.BookingDate)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.booking.BookingDate)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.booking.Status)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.booking.Status)
    </dd>
    @if (Model.flight != null)
    {
        <dt>
            @Html.DisplayNameFor(model => model.flight.FlightNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.flight.FlightNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.flight.Origin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.flight.Origin.Name) (@Html.DisplayFor(model => model.flight.Origin.IATA)), @Html.DisplayFor(model => model.flight.Origin.City), @Html.DisplayFor(model => model.flight.Origin.Country)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.flight.Dest)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.flight.Dest.Name) (@Html.DisplayFor(model => model.flight.Dest.IATA)), @Html.DisplayFor(model => model.flight.Dest.City), @Html.DisplayFor(model => model.flight.Dest.Country)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.flight.DepartureDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.flight.DepartureDateTime) hrs
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.flight.ArrivalDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.flight.ArrivalDateTime) hrs
        </dd>
        <dd>
            <span class="addtocalendar atc-style-blue">
                <var class="atc_event">
                    <var class="atc_date_start">@Model.flight.DepartureDateTime.ToString("yyyy-MM-dd HH:mm:ss")</var>
                    <var class="atc_date_end">@Model.flight.ArrivalDateTime.ToString("yyyy-MM-dd HH:mm:ss")</var>
                    <var class="atc_timezone">UTC</var>
                    <var class="atc_title">Flight @Model.flight.FlightNo to @Model.flight.Dest.City, @Model.flight.Dest.Country</var>
                    <var class="atc_description">Please be at the airport 3 hours before departure time. Enjoy your flight!</var>
                    <var class="atc_location">@Model.flight.Origin.Name (@Model.flight.Origin.IATA), @Model.flight.Origin.City, @Model.flight.Origin.Country</var>
                    <var class="atc_organizer">Ukraine International Airlines</var>
                    <var class="atc_organizer_email">fly@uia.com</var>
                </var>
            </span>
        </dd>
    }

    @if (Model.booking.Tickets != null)
    {
        <dd>
            <table class="table">
                <thead>
                    <tr>
                        <th>Ticket No</th>
                        <th>Passenger Name</th>
                        <th>Cabin Class</th>
                        <th>Price</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.booking.Tickets)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Passenger.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CabinCl)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                            <td>
                                <a asp-controller="Tickets" asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                                <a asp-controller="Tickets" asp-action="Details" asp-route-id="@item.ID">Details</a> |
                                <a asp-controller="Tickets" asp-action="Delete" asp-route-id="@item.ID">Cancel</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.booking.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.booking.Total)
        </dd>
    }

</dl>

<hr />

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script type="text/javascript">
        (function () {
                    if (window.addtocalendar)if(typeof window.addtocalendar.start == "function")return;
                    if (window.ifaddtocalendar == undefined) { window.ifaddtocalendar = 1;
                        var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
                        s.type = 'text/javascript';s.charset = 'UTF-8';s.async = true;
                        s.src = ('https:' == window.location.protocol ? 'https' : 'http')+'://addtocalendar.com/atc/1.5/atc.min.js';
                        var h = d[g]('body')[0];h.appendChild(s); }})();
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

uiaflights/uiaflights/Views/Bookings/Index.cshtml
@model IEnumerable<uiaflights.Models.Booking>

@{
    ViewData["Title"] = "Bookings";
}

<h2>Bookings</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["IdSortParm"]">@Html.DisplayNameFor(model => model.ID)</a>
</th>
            <th>
                @Html.DisplayNameFor(model => model.BookingDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.FlightNo)
</th>
            <th>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.Origin)
</th>
            <th>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.Dest)
</th>
            <th>
                @Html.DisplayNameFor(model => model.Tickets.FirstOrDefault().Flight.DepartureDateTime)
</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tickets.FirstOrDefault().Flight.FlightNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tickets.FirstOrDefault().Flight.Origin.Name) (@Html.DisplayFor(modelItem => item.Tickets.FirstOrDefault().Flight.Origin.IATA))
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tickets.FirstOrDefault().Flight.Dest.Name) (@Html.DisplayFor(modelItem => item.Tickets.FirstOrDefault().Flight.Dest.IATA))
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tickets.FirstOrDefault().Flight.DepartureDateTime) hrs
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Cancel</a>
            </td>
        </tr>
}
    </tbody>
</table>