uiaflights/uiaflights/Models/Flight.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace uiaflights.Models
{
    public class Flight
    {
        public int ID { get; set; }
        [Display(Name = "Flight No")]
        public string FlightNo { get; set; }
        public int OriginAirportID { get; set; }
        public Airport Origin { get; set; }
        public int DestAirportID { get; set; }
        [Display(Name = "Destination")]
        public Airport Dest { get; set; }
        [Display(Name = "Departure Date Time")]
        [DisplayFormat(DataFormatString = "{0:ddd, dd/MM/yyyy, HHmm}", ApplyFormatInEditMode = true)]
        public DateTime DepartureDateTime { get; set; }
        [Display(Name = "Arrival Date Time")]
        [DisplayFormat(DataFormatString = "{0:ddd, dd/MM/yyyy, HHmm}", ApplyFormatInEditMode = true)]
        public DateTime ArrivalDateTime { get; set; }
        public int PlaneID { get; set; }
        public Plane Plane { get; set; }
        public ICollection<Ticket> Tickets { get; set; }
        public ICollection<Tariff> Tariff { get; set; }
    }
}

uiaflights/uiaflights/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using uiaflights.Data;
using uiaflights.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using uiaflights.Models.FlightBookingViewModels;

namespace uiaflights.Controllers
{
    public class FlightsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public FlightsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Flights
        //public async Task<IActionResult> Index()
        //{
        //    var applicationDbContext = _context.Flights
        //        .Include(f => f.Dest)
        //        .Include(f => f.Origin)
        //        .Include(f => f.Plane);
        //    return View(await applicationDbContext.ToListAsync());
        //}

        public async Task<IActionResult> Search(string origin, string dest, string date, string sortOrder)
        {
            ViewData["origin"] = new SelectList(_context.Airports, "Name", "Name", origin);
            ViewData["originvalue"] = origin;
            ViewData["dest"] = new SelectList(_context.Airports, "Name", "Name", dest);
            ViewData["destvalue"] = dest;
            ViewData["date"] = date;
            ViewData["DateSortParm"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
            ViewData["EconSortParm"] = sortOrder == "econ_asc" ? "econ_desc" : "econ_asc";
            ViewData["BusSortParm"] = sortOrder == "bus_asc" ? "bus_desc" : "bus_asc";
            ViewData["FirstSortParm"] = sortOrder == "first_asc" ? "first_desc" : "first_asc";

            if (!String.IsNullOrEmpty(origin) && !String.IsNullOrEmpty(dest) && !String.IsNullOrEmpty(date))
            {
                var flights = from f in _context.Flights
                              .Include(f => f.Dest)
                              .Include(f => f.Origin)
                              .Include(f => f.Plane)
                              .Include(f => f.Tariff)
                              select f;

                if (!String.IsNullOrEmpty(origin))
                {
                    flights = flights.Where(f => f.Origin.IATA.Contains(origin) || f.Origin.Name.Contains(origin));
                }
                if (!String.IsNullOrEmpty(dest))
                {
                    flights = flights.Where(f => f.Dest.IATA.Contains(dest) || f.Dest.Name.Contains(dest));
                }
                if (!String.IsNullOrEmpty(date))
                {
                    DateTime departDate = DateTime.Parse(date);
                    if(departDate.Date <= DateTime.Now.Date)
                    {
                        ViewData["ErrorMessage"] = "Invalid Date! Flights are available for bookings from " + DateTime.Now.AddDays(1).Date.ToString() + " onwards.";
                        return View();
                    }
                    flights = flights.Where(f => f.DepartureDateTime >= departDate && f.DepartureDateTime <= departDate.AddDays(14));
                }
                switch (sortOrder)
                {
                    case "econ_desc":
                        flights = flights.OrderByDescending(f => f.Tariff.Single(t => t.CabinCl == "Economy").AdultFare);
                        break;
                    case "econ_asc":
                        flights = flights.OrderBy(f => f.Tariff.Single(t => t.CabinCl == "Economy").AdultFare);
                        break;
                    case "bus_desc":
                        flights = flights.OrderByDescending(f => f.Tariff.Single(t => t.CabinCl == "Business").AdultFare);
                        break;
                    case "bus_asc":
                        flights = flights.OrderBy(f => f.Tariff.Single(t => t.CabinCl == "Business").AdultFare);
                        break;
                    case "first_desc":
                        flights = flights.OrderByDescending(f => f.Tariff.Single(t => t.CabinCl == "First").AdultFare);
                        break;
                    case "first_asc":
                        flights = flights.OrderBy(f => f.Tariff.Single(t => t.CabinCl == "First").AdultFare);
                        break;
                    case "date_desc":
                        flights = flights.OrderByDescending(f => f.DepartureDateTime);
                        break;
                    default:
                        flights = flights.OrderBy(f => f.DepartureDateTime);
                        break;
                }
                return View(await flights.AsNoTracking().ToListAsync());
            }
            else
            {
                ViewData["ErrorMessage"] = "Please enter Origin, Destination, and Date (earliest is the next day) to search for flights!";
                return View();
            }

        }

        // GET: Flights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .Include(f => f.Dest)
                .Include(f => f.Origin)
                .Include(f => f.Plane)
                .AsNoTracking()
                .Include(f => f.Tickets).ThenInclude(t => t.Passenger).AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        //// GET: Flights/Create
        //public IActionResult Create()
        //{
        //    ViewData["DestAirportID"] = new SelectList(_context.Airports, "AirportID", "AirportID");
        //    ViewData["OriginAirportID"] = new SelectList(_context.Airports, "AirportID", "AirportID");
        //    ViewData["PlaneID"] = new SelectList(_context.Planes, "ID", "ID");
        //    return View();
        //}

        //// POST: Flights/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("ID,FlightNo,OriginAirportID,DestAirportID,DepartureDateTime,ArrivalDateTime,PlaneID")] Flight flight)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(flight);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }
        //    ViewData["DestAirportID"] = new SelectList(_context.Airports, "AirportID", "AirportID", flight.DestAirportID);
        //    ViewData["OriginAirportID"] = new SelectList(_context.Airports, "AirportID", "AirportID", flight.OriginAirportID);
        //    ViewData["PlaneID"] = new SelectList(_context.Planes, "ID", "ID", flight.PlaneID);
        //    return View(flight);
        //}

        //// GET: Flights/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var flight = await _context.Flights.SingleOrDefaultAsync(m => m.ID == id);
        //    if (flight == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["DestAirportID"] = new SelectList(_context.Airports, "AirportID", "AirportID", flight.DestAirportID);
        //    ViewData["OriginAirportID"] = new SelectList(_context.Airports, "AirportID", "AirportID", flight.OriginAirportID);
        //    ViewData["PlaneID"] = new SelectList(_context.Planes, "ID", "ID", flight.PlaneID);
        //    return View(flight);
        //}

        //// POST: Flights/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("ID,FlightNo,OriginAirportID,DestAirportID,DepartureDateTime,ArrivalDateTime,PlaneID")] Flight flight)
        //{
        //    if (id != flight.ID)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(flight);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!FlightExists(flight.ID))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction("Index");
        //    }
        //    ViewData["DestAirportID"] = new SelectList(_context.Airports, "AirportID", "AirportID", flight.DestAirportID);
        //    ViewData["OriginAirportID"] = new SelectList(_context.Airports, "AirportID", "AirportID", flight.OriginAirportID);
        //    ViewData["PlaneID"] = new SelectList(_context.Planes, "ID", "ID", flight.PlaneID);
        //    return View(flight);
        //}

        //// GET: Flights/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

uiaflights/uiaflights/Views/Flights/Book.cshtml
@model uiaflights.Models.FlightBookingViewModels.FlightBookingViewModel


@{
    ViewData["Title"] = "Book Flight";
}

@section Styles {
    <link href="https://addtocalendar.com/atc/1.5/atc-style-blue.css" rel="stylesheet" type="text/css">
}

<h2>Book Flight</h2>

<hr />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.flight.FlightNo)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.flight.FlightNo)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.flight.Origin)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.flight.Origin.Name) (@Html.DisplayFor(model => model.flight.Origin.IATA)), @Html.DisplayFor(model => model.flight.Origin.City), @Html.DisplayFor(model => model.flight.Origin.Country)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.flight.Dest)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.flight.Dest.Name) (@Html.DisplayFor(model => model.flight.Dest.IATA)), @Html.DisplayFor(model => model.flight.Dest.City), @Html.DisplayFor(model => model.flight.Dest.Country)
<dt>
        @Html.DisplayNameFor(model => model.flight.DepartureDateTime)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.flight.DepartureDateTime) hrs
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.flight.ArrivalDateTime)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.flight.ArrivalDateTime) hrs
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.flight.Plane)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.flight.Plane.Make) @Html.DisplayFor(model => model.flight.Plane.Model) | @Html.DisplayFor(model => model.flight.Plane.TailNo)
    </dd>
    <dd>
        <span class="addtocalendar atc-style-blue">
            <var class="atc_event">
                <var class="atc_date_start">@Model.flight.DepartureDateTime.ToString("yyyy-MM-dd HH:mm:ss")</var>
                <var class="atc_date_end">@Model.flight.ArrivalDateTime.ToString("yyyy-MM-dd HH:mm:ss")</var>
                <var class="atc_timezone">UTC</var>
                <var class="atc_title">Flight @Model.flight.FlightNo to @Model.flight.Dest.City, @Model.flight.Dest.Country</var>
                <var class="atc_description">Please be at the airport 3 hours before departure time. Enjoy your flight!</var>
                <var class="atc_location">@Model.flight.Origin.Name (@Model.flight.Origin.IATA), @Model.flight.Origin.City, @Model.flight.Origin.Country</var>
                <var class="atc_organizer">Ukraine International Airlines</var>
                <var class="atc_organizer_email">fly@uia.com</var>
            </var>
        </span>
    </dd>
</dl>

<hr />
@if (ViewData["Message"] != null)
{
    <div class="alert alert-success">
        <strong>@ViewData["Message"]</strong>
    </div>
}
<br />

<form asp-controller="Flights" asp-action="Book">
    <div class="form-horizontal">
        <input type="hidden" asp-for="flight.ID" name="fid"/>
        <input type="hidden" asp-for="booking.ID" name="bid" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Gender" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DOB" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DOB" class="form-control" />
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PassportNo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PassportNo" class="form-control" />
                <span asp-validation-for="PassportNo" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Nationality" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Nationality" class="form-control" />
                <span asp-validation-for="Nationality" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="cabinCl" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select name="cabinCl" class="form-control" asp-items="ViewBag.ClassType"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Book" class="btn btn-default" /> |
                <a asp-action="Search" asp-route-origin="@ViewData["origin"]" asp-route-dest="@ViewData["dest"]" asp-route-date="@ViewData["date"]">Back to List</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <script type="text/javascript">
    (function () {
                if (window.addtocalendar)if(typeof window.addtocalendar.start == "function")return;
                if (window.ifaddtocalendar == undefined) { window.ifaddtocalendar = 1;
                    var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
                    s.type = 'text/javascript';s.charset = 'UTF-8';s.async = true;
                    s.src = ('https:' == window.location.protocol ? 'https' : 'http')+'://addtocalendar.com/atc/1.5/atc.min.js';
                    var h = d[g]('body')[0];h.appendChild(s); }})();
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

uiaflights/uiaflights/Views/Flights/Create.cshtml
@model uiaflights.Models.Flight

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Flight</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="FlightNo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FlightNo" class="form-control" />
                <span asp-validation-for="FlightNo" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="OriginAirportID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="OriginAirportID" class="form-control" asp-items="ViewBag.OriginAirportID"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DestAirportID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="DestAirportID" class="form-control" asp-items="ViewBag.DestAirportID"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DepartureDateTime" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DepartureDateTime" class="form-control" />
                <span asp-validation-for="DepartureDateTime" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ArrivalDateTime" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ArrivalDateTime" class="form-control" />
                <span asp-validation-for="ArrivalDateTime" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PlaneID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="PlaneID" class="form-control" asp-items="ViewBag.PlaneID"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

uiaflights/uiaflights/Views/Flights/Delete.cshtml
@model uiaflights.Models.Flight

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.FlightNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FlightNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Origin.Name) (@Html.DisplayFor(model => model.Origin.IATA))
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Dest)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Dest.Name) (@Html.DisplayFor(model => model.Dest.IATA))
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartureDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartureDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArrivalDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Plane)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Plane.Make) @Html.DisplayFor(model => model.Plane.Model) | @Html.DisplayFor(model => model.Plane.TailNo)
        </dd>
        @if (Model.Tickets != null)
        {
            <dd>
                <table class="table">
                    <tr>
                        <th>Passenger Name</th>
                        <th>Cabin Class</th>
                    </tr>
                    @foreach (var item in Model.Tickets)
                {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Passenger.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CabinCl)
                            </td>
                        </tr>
                    }
                </table>
            </dd>
        }
    </dl>

    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

uiaflights/uiaflights/Views/Flights/Details.cshtml
@model uiaflights.Models.Flight

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Flight</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FlightNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FlightNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Origin.Name) (@Html.DisplayFor(model => model.Origin.IATA))
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Dest)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Dest.Name) (@Html.DisplayFor(model => model.Dest.IATA))
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartureDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepartureDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ArrivalDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Plane)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Plane.Make) @Html.DisplayFor(model => model.Plane.Model) | @Html.DisplayFor(model => model.Plane.TailNo)
        </dd>
        <dd>
            <table class="table">
                <tr>
                    <th>Passenger Name</th>
                    <th>Cabin Class</th>
                </tr>
                @foreach (var item in Model.Tickets)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Passenger.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CabinCl)
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

uiaflights/uiaflights/Views/Flights/Edit.cshtml
@model uiaflights.Models.Flight

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Flight</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="FlightNo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FlightNo" class="form-control" />
                <span asp-validation-for="FlightNo" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Origin" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="OriginAirportID" class="form-control" asp-items="ViewBag.OriginAirportID"></select>
                <span asp-validation-for="OriginAirportID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Dest" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="DestAirportID" class="form-control" asp-items="ViewBag.DestAirportID"></select>
                <span asp-validation-for="DestAirportID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="DepartureDateTime" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DepartureDateTime" class="form-control" />
                <span asp-validation-for="DepartureDateTime" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ArrivalDateTime" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ArrivalDateTime" class="form-control" />
                <span asp-validation-for="ArrivalDateTime" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Plane" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="PlaneID" class="form-control" asp-items="ViewBag.PlaneID"></select>
                <span asp-validation-for="PlaneID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

uiaflights/uiaflights/Views/Flights/Index.cshtml
@model IEnumerable<uiaflights.Models.Flight>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Origin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dest)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArrivalDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Plane)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Origin.Name) (@Html.DisplayFor(modelItem => item.Origin.IATA))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dest.Name) (@Html.DisplayFor(modelItem => item.Dest.IATA))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlightNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureDateTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ArrivalDateTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Plane.Model)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>