uiaflights/uiaflights/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace uiaflights.Models
{
    public class Ticket
    {
        public int ID { get; set; }
        public int FlightID { get; set; }
        public int PassengerId { get; set; }
        public Flight Flight { get; set; }
        public Passenger Passenger { get; set; }
        public Booking Booking { get; set; }
        [Display(Name = "Cabin Class")]
        public string CabinCl { get; set; }
        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        public decimal Price { get; set; }
    }
}

uiaflights/uiaflights/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using uiaflights.Data;
using uiaflights.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using uiaflights.Models.FlightBookingViewModels;

namespace uiaflights.Controllers
{
    [Authorize]
    public class BookingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public BookingsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Bookings
        public async Task<IActionResult> Index(string sortOrder)
        {
            var user = await _userManager.GetUserAsync(User);
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            //ViewData["FlightSortParm"] = sortOrder == "flight_asc" ? "flight_desc" : "flight_asc";
            //ViewData["OriginSortParm"] = sortOrder == "origin_asc" ? "origin_desc" : "origin_asc";
            //ViewData["DestSortParm"] = sortOrder == "dest_asc" ? "dest_desc" : "dest_asc";
            //ViewData["DateSortParm"] = sortOrder == "date_asc" ? "date_desc" : "date_asc";
            var bookings = from b in _context.Bookings
                           .Include(b => b.Customer)
                           .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Origin)
                           .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Dest)
                           .Include(b => b.Tickets).ThenInclude(t => t.Passenger)
                           .Where(b => b.Customer == (Customer)user)
                           select b;
            switch (sortOrder)
            {
                //case "date_desc":
                //    bookings = bookings.OrderByDescending(b => b.Tickets.FirstOrDefault().Flight.DepartureDateTime);
                //    break;
                //case "date_asc":
                //    bookings = bookings.OrderBy(b => b.Tickets.FirstOrDefault().Flight.DepartureDateTime);
                //    break;
                //case "dest_desc":
                //    bookings = bookings.OrderByDescending(b => b.Tickets.FirstOrDefault().Flight.Dest.Name);
                //    break;
                //case "dest_asc":
                //    bookings = bookings.OrderBy(b => b.Tickets.FirstOrDefault().Flight.Dest.Name);
                //    break;
                //case "origin_desc":
                //    bookings = bookings.OrderByDescending(b => b.Tickets.FirstOrDefault().Flight.Origin.Name);
                //    break;
                //case "origin_asc":
                //    bookings = bookings.OrderBy(b => b.Tickets.FirstOrDefault().Flight.Origin.Name);
                //    break;
                //case "flight_desc":
                //    bookings = bookings.OrderByDescending(b => b.Tickets.FirstOrDefault().Flight.FlightNo);
                //    break;
                //case "flight_asc":
                //    bookings = bookings.OrderBy(b => b.Tickets.FirstOrDefault().Flight.FlightNo);
                //    break;
                //case "id_desc":
                //    bookings = bookings.OrderByDescending(b => b.ID);
                //    break;
                default:
                    bookings = bookings.OrderBy(b => b.ID);
                    break;
            }
            return View(await bookings.AsNoTracking().ToListAsync());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Customer)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Origin)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Dest)
                .Include(b => b.Tickets).ThenInclude(t => t.Passenger)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return NotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Customer)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Origin)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Dest)
                .Include(b => b.Tickets).ThenInclude(t => t.Passenger)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return NotFound();
            }
            FlightBookingViewModel fbvm = new FlightBookingViewModel
            {
                flight = booking.Tickets.FirstOrDefault().Flight,
                booking = booking
            };
            return View(fbvm);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Customer)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Origin)
                .Include(b => b.Tickets).ThenInclude(t => t.Flight).ThenInclude(f => f.Dest)
                .Include(b => b.Tickets).ThenInclude(t => t.Passenger)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again, and if the problem persists " +
                    "see your system administrator.";
            }

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var booking = await _context.Bookings
                .Include(b => b.Tickets)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (booking == null)
            {
                return RedirectToAction("Index");
            }
            try
            {
                var tickets = booking.Tickets;
                foreach (Ticket t in tickets)
                {
                    _context.Tickets.Remove(t);
                }
                _context.Bookings.Remove(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.)
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
        }

        private bool BookingExists(int id)
        {
            return _context.Bookings.Any(e => e.ID == id);
        }
    }
}

uiaflights/uiaflights/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using uiaflights.Data;
using uiaflights.Models;
using Microsoft.AspNetCore.Identity;

namespace uiaflights.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public TicketsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Passenger)
                .Include(t => t.Booking)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Passenger)
                .Include(t => t.Booking)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (ticket == null)
            {
                return NotFound();
            }
            IEnumerable<string> classType = new string[] { "Economy", "Business", "First" };
            ViewData["ClassType"] = new SelectList(classType, ticket.CabinCl);
            return View(ticket);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ticketToUpdate = await _context.Tickets
                .Include(t => t.Passenger)
                .Include(t => t.Booking)
                .Include(t => t.Flight).ThenInclude(f => f.Tariff)
                .SingleOrDefaultAsync(t => t.ID == id);
            var bookingUrl = "/Bookings/Edit/" + ticketToUpdate.Booking.ID;
            if (await TryUpdateModelAsync<Ticket>(
                ticketToUpdate,
                "",
                t => t.Passenger, t => t.CabinCl))
            {
                try
                {
                    var oldPrice = ticketToUpdate.Price;
                    ticketToUpdate.Price = ticketToUpdate.Flight.Tariff.Single(t => t.CabinCl == ticketToUpdate.CabinCl).AdultFare;
                    ticketToUpdate.Booking.Total = ticketToUpdate.Booking.Total - oldPrice + ticketToUpdate.Price;
                    await _context.SaveChangesAsync();
                    return Redirect(bookingUrl);
                }
                catch (DbUpdateException /* ex */)
                {
                    //Log the error (uncomment ex variable name and write a log.)
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
            }
            IEnumerable<string> classType = new string[] { "Economy", "Business", "First" };
            ViewData["ClassType"] = new SelectList(classType, ticketToUpdate.CabinCl);
            return View(ticketToUpdate);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Passenger)
                .Include(t => t.Booking)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);
            if (ticket == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again, and if the problem persists " +
                    "see your system administrator.";
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Tickets
                .Include(t => t.Booking)
                .SingleOrDefaultAsync(m => m.ID == id);
            var bookingUrl = "/Bookings/Edit/" + ticket.Booking.ID;
            if (ticket == null)
            {
                return Redirect(bookingUrl);
            }
            try
            {
                ticket.Booking.Total = ticket.Booking.Total - ticket.Price;
                _context.Update(ticket.Booking);
                _context.Tickets.Remove(ticket);
                await _context.SaveChangesAsync();
                return Redirect(bookingUrl);
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.)
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.ID == id);
        }
    }
}

uiaflights/uiaflights/Views/Tickets/Delete.cshtml
@model uiaflights.Models.Ticket

@{
    ViewData["Title"] = "Cancel Ticket";
}

<h2>Cancel Ticket</h2>
<p class="text-danger">@ViewData["ErrorMessage"]</p>

<h3>Are you sure you want to cancel this ticket?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.DOB)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.DOB)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.PassportNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.PassportNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.Nationality)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.Nationality)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CabinCl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CabinCl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Cancel" class="btn btn-default" /> |
            <a asp-controller="Bookings" asp-action="Edit" asp-route-id="@Model.Booking.ID">Back</a>
        </div>
    </form>
</div>

uiaflights/uiaflights/Views/Tickets/Details.cshtml
@model uiaflights.Models.Ticket

@{
    ViewData["Title"] = "Ticket Details";
}

<h2>Ticket Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.DOB)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.DOB)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.PassportNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.PassportNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Passenger.Nationality)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Passenger.Nationality)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CabinCl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CabinCl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-controller="Bookings" asp-action="Edit" asp-route-id="@Model.Booking.ID">Back</a>
</div>

uiaflights/uiaflights/Views/Tickets/Edit.cshtml
@model uiaflights.Models.Ticket

@{
    ViewData["Title"] = "Edit Ticket";
}

<h2>Edit Ticket</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="Passenger.Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Passenger.Name" class="form-control" />
                <span asp-validation-for="Passenger.Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Passenger.Gender" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Passenger.Gender" class="form-control" />
                <span asp-validation-for="Passenger.Gender" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Passenger.Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Passenger.Phone" class="form-control" />
                <span asp-validation-for="Passenger.Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Passenger.Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Passenger.Email" class="form-control" />
                <span asp-validation-for="Passenger.Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Passenger.DOB" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Passenger.DOB" class="form-control" />
                <span asp-validation-for="Passenger.DOB" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Passenger.PassportNo" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Passenger.PassportNo" class="form-control" />
                <span asp-validation-for="Passenger.PassportNo" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Passenger.Nationality" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Passenger.Nationality" class="form-control" />
                <span asp-validation-for="Passenger.Nationality" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="cabinCl" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select name="cabinCl" class="form-control" asp-items="ViewBag.ClassType"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-controller="Bookings" asp-action="Edit" asp-route-id="@Model.Booking.ID">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}